"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SpeechProduction = exports.SpeechRecognition = exports.SignRecognition = exports.SignProduction = void 0;
var SignProduction_1 = require("./stories/SignProduction");
Object.defineProperty(exports, "SignProduction", { enumerable: true, get: function () { return SignProduction_1.SignProduction; } });
var SignRecognition_1 = require("./stories/SignRecognition");
Object.defineProperty(exports, "SignRecognition", { enumerable: true, get: function () { return SignRecognition_1.SignRecognition; } });
var SpeechRecognition_1 = require("./stories/SpeechRecognition");
Object.defineProperty(exports, "SpeechRecognition", { enumerable: true, get: function () { return SpeechRecognition_1.SpeechRecognition; } });
var SpeechProduction_1 = require("./stories/SpeechProduction");
Object.defineProperty(exports, "SpeechProduction", { enumerable: true, get: function () { return SpeechProduction_1.SpeechProduction; } });
